### ISSUE TITLE
Please learn about structs and struct packing (and EVM gas costs in general)

### ISSUE THREAD

**Issue by boringcrypto** [keep3r-network/keep3r-network-v2#3]
https://github.com/keep3r-network/keep3r-network-v2/blob/cdd28f3da309af9eb18b6abe03ea139155d0aefb/solidity/interfaces/peripherals/IKeep3rAccountance.sol#L27

Start here:
https://docs.soliditylang.org/en/v0.8.11/internals/layout_in_storage.html
https://fravoll.github.io/solidity-patterns/tight_variable_packing.html

**Comment by 0xGorilla** [comment]
Hey @boringcrypto ! Please expand on the possible ways to improve the Keep3r Network, it would be very constructive.

As of now, I will proceed to close this issue.
